# This is a basic workflow to help you get started with Actions

name: ðŸš€ Deploy website on push
 
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  web-deploy:
    # The type of runner that the job will run on
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: ðŸšš Get latest code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with: 
         server: ${{secrets.FTP_SERVER}}
         username: ${{secrets.FTP_USERNAME}}
         password: ${{secrets.FTP_PASSWORD}}
         port: 21 # todo replace with your web hosts ftps port
         exclude: |
          **/node_modules/**
          **/.htaccess/**
          **/.git*
          **/.git*/**
          .htaccess
